version: '3'

services:
  # App
  app:
    build:
      context: .
      target: development
      dockerfile: ./dockerfile
    container_name: 'nest_typeorm'
    command: npm run start:dev
    ports:
      - ${APP_PORT}:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql
    env_file: ./.env
    networks:
      - backend

  # Database
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PW}
      MYSQL_DATABASE: ${DATABASE_DB}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PW}
    env_file: ./.env
    ports:
      - '13306:3306'
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/conf.d:/etc/mysql/mysql.conf.d/
    restart: always
    networks:
      - backend

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - '8081:80'
    networks:
      - backend

networks:
  backend:
    driver: bridge
