version: '3'

services:
  # Database
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DATABASE_PW
      MYSQL_DATABASE: $DATABASE_DB
    env_file: ./.env
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - backend

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - '8081:80'
    networks:
      - backend
  # App
  app:
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    container_name: 'nest_typeorm'
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mysql
    env_file: ./.env
    environment:
      - DATABASE_DRIVER=$DATABASE_DRIVER
      - DATABASE_HOST=$DATABASE_HOST
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_USER=$DATABASE_USER
      - DATABASE_PW=$DATABASE_PW
      - DATABASE_DB=$DATABASE_DB
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
    driver: local
