version: '3'

services:
  # app
  app:
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    container_name: 'nest_typeorm'
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DD_AGENT_HOST=datadog_agent
    # NODE_ENV: "dev"
    env_file: ./.env
    networks:
      - backend

  # Database
  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0111mvtT
      MYSQL_DATABASE: nest_typeorm
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=caching_sha2_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - backend

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - '8081:80'
    networks:
      - backend

networks:
  backend:
    driver: bridge
volumes:
  db_data:
